//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTools.Service.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Runtime.Remoting.Messaging;

    public partial class SM_Module : DbContext
    {
        public SM_Module()
            : base("name=SM_ModuleContainer")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<UserInfo> UserInfo { get; set; }
    }

    public static class DbContainer
    {
        public static SM_Module GetDbContext()
        {
            var dbContext = CallContext.GetData("DbContext");
            if (dbContext == null)
            {
                CallContext.SetData("DbContext", dbContext);
            }

            return dbContext as SM_Module;
        }
    }
}
