//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTools.Service.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserPwd { get; set; }
        public System.TimeSpan CreateDate { get; set; }
        public float IsActivation { get; set; }
        public string ActivationLevel { get; set; }
        public System.TimeSpan ActivationDate { get; set; }
    }
}
